name: Build & Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write         # allow configuring & publishing Pages
      id-token: write      # required by configure-pages action

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        run: |
          echo "VITE_OPENROUTER_API_KEY=${{ secrets.OPENROUTER_KEY }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Copy resources into build output
        run: |
          mkdir -p dist/mesh
          cp -R mesh/* dist/mesh/
          mkdir -p dist/MCMRSimulator_Public_API_Document
          cp -R MCMRSimulator_Public_API_Document/* dist/MCMRSimulator_Public_API_Document/
          mkdir -p dist/MRIBuilder_Public_API_Document
          cp -R MRIBuilder_Public_API_Document/* dist/MRIBuilder_Public_API_Document/

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist       # Vite’s default output folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: dist
